// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdFe9YQ0UZ_5nbkyUxVPTde9RexNPrK_k',
    appId: '1:344932390884:web:bef95c0b8bb5f17f9f19f1',
    messagingSenderId: '344932390884',
    projectId: 'flutter3-fe413',
    authDomain: 'flutter3-fe413.firebaseapp.com',
    storageBucket: 'flutter3-fe413.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk1p9iF2vntzzGb1uOuO-vOgikOqDwK08',
    appId: '1:344932390884:android:35b073e525c877649f19f1',
    messagingSenderId: '344932390884',
    projectId: 'flutter3-fe413',
    storageBucket: 'flutter3-fe413.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_9ExltfbFafzHp_l0kZoRuxC5k-QE7LQ',
    appId: '1:344932390884:ios:0f084910eb4f67a29f19f1',
    messagingSenderId: '344932390884',
    projectId: 'flutter3-fe413',
    storageBucket: 'flutter3-fe413.appspot.com',
    iosClientId: '344932390884-ul8sv7t933jagqvp0f5kn3rrk85feeg3.apps.googleusercontent.com',
    iosBundleId: 'fr.fittinghome.fittinghomescannerpro',
  );
}
